Models/Card.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication2.Models{
    public class Card{
        public int CardID { get; set; }
        [Display(Name = "Card Name")]
        public string Name { get; set; }
        public string Type { get; set; }
        public string Color { get; set; }
        public string Artist { get; set; }
        public string Image { get; set; }
        public int CMC { get; set; }
        public int Rarity { get; set; } 
        public int? Power { get; set; }
        public int? Toughness { get; set; }
        public string SetCode { get; set; }
        [DataType(DataType.Date)]
        public DateTime? DeletedAt { get; set; }

        //public Set set { get; set; }



        public override string ToString() {
            return Name;}
        
    }
}

Controllers/CardsController.cs
using System;
using System.Collections.ObjectModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ORM_library.Objects;
using ORM_library.Tables;
using WebApplication2.Models;
using WebApplication2.ViewModels;

namespace WebApplication2.Controllers{
    public class CardsController : Controller{


        //GET: Cards
        public IActionResult Index() {
            var bds = new DecksTable().Select_best();
            var ds = new DecksTable().Select();

            var cs = new CardsTable().Select_cards_most_rating_player();

            var model = new CardIndexForm {
                CardList = new CardListViewModel {Cards = GimmeCards(cs)},
                DeckList = new DeckListViewModel {Decks = DecksController.GimmeDecks(bds)},
                DeckSelect = new DeckSelectViewModel {Decks = new SelectList(DecksController.GimmeDecks(ds), "DeckID", "Name")}


            };

            
            return View("Index",model);
        }
        [HttpPost]
        public RedirectToActionResult Index(CardIndexForm model, string CardID) { //Jak sem dostat CardID z několika submitů - každý ho má jiné
            if ( CardID != "0") {
                Console.WriteLine("------------------------------FKLIDU-----------------------------------"+model.DeckSelect.SelectedDeck.DeckID);
            }
            else {
                Console.WriteLine("-------------------------------CARDID=0?-------------------------------------");
            }

            return RedirectToAction("Index");
        }
        
/*    public IActionResult AddCardToDeck(int DeckID, int CardID) {
        
        var model = new CardDeck {CardID = CardID, DeckID = DeckID, Count = 1};
          
            Console.WriteLine("------------------------D"+DeckID+", C"+CardID);
            return View("AddCardToDeck",model);
            
        }

    [HttpPost]
    public RedirectToActionResult AddCardToDeck(CardDeck model, int DeckID, int CardID) {
        var model = new CardDeck {CardID = CardID, DeckID = DeckID, Count = 1};
        return RedirectToAction("AddCardToDeck");
    }*/

        //GET: Cards/detail?multiverseid=3
        public IActionResult Detail(int multiverseID) {
            ViewData["MultiverseID"] = multiverseID;
            try {

                var card = new CardsTable().Select_by_id(multiverseID);

                var karta = new Card {
                    CardID = multiverseID,
                    Name = card.name,
                    Type = card.type,
                    Color = card.color,
                    Artist = card.artist,
                    Image = card.image,
                    CMC = card.cmc,
                    Rarity = card.rarity,
                    Power = card.power,
                    Toughness = card.toughness,
                    SetCode = card.set_code,
                    DeletedAt = card.deleted_at
                };


                return View(karta);
            }
            catch {
                return View(new Card {
                    Artist = "Not in database", CardID = multiverseID, CMC = 666, Color = "Not in database",
                    DeletedAt = null, Image = "Not in database", Name = "Not in database", SetCode = "Not in database",
                    Rarity = 0, Type = "Not in database"
                });
            }
            
        }

//GET: Cards/cardslist
        public IActionResult CardsList() {
            var cs = new CardsTable().Select();

            CardListViewModel model = new CardListViewModel {Cards = GimmeCards(cs)};
            return View(model);
        }

//GET:Cards/CardSearch
        public IActionResult CardsSearch(string searchStr) {
            ViewData["SearchStr"] = searchStr;
            var cs = new CardsTable().Select_by_name(searchStr);

            CardListViewModel model = new CardListViewModel {Cards = GimmeCards(cs)};
            return View(model);
        }

      

        public static Collection<Card> GimmeCards(Collection<Cards> cardsTableSelect) {
            var cards = new Collection<Card>();
            foreach (var c in cardsTableSelect) {
                var card = new Card {
                    CardID = c.card_id,
                    Name = c.name,
                    Type = c.type,
                    Color = c.color,
                    Artist = c.artist,
                    Image = c.image,
                    CMC = c.cmc,
                    Rarity = c.rarity,
                    Power = c.power,
                    Toughness = c.toughness,
                    SetCode = c.set_code,
                    DeletedAt = c.deleted_at
                };
                cards.Add(card);
            }

            return cards;
        }

    }
}

Controllers/DecksController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ORM_library.Objects;
using ORM_library.Tables;
using WebApplication2.Models;
using WebApplication2.ViewModels;


namespace WebApplication2.Controllers{
    public class DecksController : Controller{
        // GET
        public IActionResult Index() {
            var ds = new DecksTable().SelectWithoutDeleted();
            var model = new DeckListViewModel {Decks = GimmeDecks(ds)};
            return View(model);
        }

        // GET Decks/Detail
        public IActionResult Detail(int id) {
            var model = new DeckDetailForm();
            fillModel(model, id);

            return View("Detail", model);
        }

        [HttpPost]
        public RedirectToActionResult Detail(DeckDetailForm model, int id) {
            if (model.Rating != null) {
                var rat = new Ratings(model.Rating.Stars, model.Rating.PlayerID, id);
                Console.WriteLine(rat);
                 new RatingsTable().Rate(rat);

            }
            else{
           
            Change change = null;
           /* if (string.IsNullOrEmpty(model.Comment.Text)) {
                ModelState.AddModelError("Comment.Text","You have to type some text to add a comment");
            }

            if (model.Comment.PlayerID == -1) {
                ModelState.AddModelError("Comment.PlayerID","You have to select the author");

            }*/
            Console.WriteLine("---------------------------------------------------------------------------------");
            ModelState.Remove("Change.Count");
            ModelState.Remove("Change.Card.CardID");
            if (ModelState.IsValid) {
                var authorID = model.Comment.PlayerID;
                var text = model.Comment.Text;
                bool recChange = model.Comment.isChangeRecommended;
                var c = new Comments {
                    added_at = DateTime.Now, deck_id = id, player_id = authorID,
                    text = model.Comment.Text, deleted_at = null
                };
                
//comment insert
                new CommentsTable().Add_comment(c);
                
                var comid = new CommentsTable().Select_max_ID();
                
                if (recChange) {
                   // if (ModelState["Change.Count"].ValidationState == ModelValidationState.Valid) {
                      //  if (ModelState["Change.Card.CardID"].ValidationState == ModelValidationState.Valid) {
                            change = new Change {
                                Card = model.Change.Card,
                                CardID = model.Change.Card.CardID,
                                ChangeType = model.Change.ChangeType,
                                Comment = model.Comment,
                                CommentID = comid,
                                Count = model.Change.Count
                            };
//Change insert
                            new ChangesTable().Insert(new Changes(change.ChangeType,change.CardID, comid, change.Count ));
                        //}
                       // else {ModelState.AddModelError("Change.Count","Počet karet musí být mezi 0 a 4 pokud karta není land");}
                        
                   // }
                    //else {ModelState.AddModelError("Change.Card.CardID","You must select card for a change");}
                    

                    Console.WriteLine("Text=" + text + ",author=" + authorID + ", Change recommended\n" +
                                      "\tChange type=" + change.ChangeType + ", for card:" + change.CardID + ": " +
                                      change.Count + "times");
                }
                else {
                    Console.WriteLine("Text=" + text + ",author=" + authorID + ", Change not recommended");
                }


                

                /*    if (model.Comment.isChangeRecommended) {
                        Console.WriteLine(
                            new ChangesTable().Insert(
                                new Changes(
                                    model.Change.ChangeType,
                                    model.CardSelect.SelectedCard.CardID,
                            comid,
                                    model.Change.Count
                        )));
                        
                    }*/
/*                Console.WriteLine(now+": CommentID:"+comid+
                                  ", DeckID:"+did+", PlayerID:"+authorID+", text:"+text);
*/
                return RedirectToAction("Detail");
            }}

            

            Console.WriteLine("---------------------------------------------------------------------------------");


            return RedirectToAction("Detail", model);
            //return View("Detail",model);
        }

        public IActionResult Create() {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Deck model) {
            try {
                if (!ModelState.IsValid) return View();
                ViewData["Name"] = model.Name;
                ViewData["Description"] = model.Description;
                ViewData["PlayerID"] = model.PlayerID;

                return View("Index");
            }
            catch {
                return View();
            }
        }

        private DeckDetailForm fillModel(DeckDetailForm model, int ID) {
            var ct = new CardsTable();
            var pt = new PlayersTable();
            var cdt = new Card_deckTable();
            Dictionary<Card, int> cardsWCount = new Dictionary<Card, int>();

            var cds = cdt.Select();
            var ps = pt.Select(); //Select všech hráčů
            var d = new DecksTable().Select(ID); //Select decku
            var cs = new CardsTable().Select_by_deck_id(ID); //Select karet v decku
            var coms = new CommentsTable().Select_by_deck_id(ID); //Select komentářů k decku
        
            var avgCmc = ct.Select_avg_cmc(ID);
            var typeRat = ct.Select_type_ratio(d);
            var coloreRat = ct.Select_color_ratio(d);
            
            
            var cards = CardsController.GimmeCards(cs);
            var players = PlayersController.GimmePlayers(ps);
            var comments = CommentsController.GimmeComments(coms);
             foreach (var c in comments) {
                 var author = pt.Select_by_id(c.PlayerID);
                 c.Author = new Player {
                     DeletedAt = author.deleted_at, Login = author.login, Note = author.note,
                     Password = author.password, PlayerID = author.player_id, Registered = author.registered
                 };
             }
            
             var ranks = new RanksTable().Select();
             var rank = "No rank yet";
             if (d.stars.HasValue) {
                rank = ranks[(int) d.stars].rank_name;}
             
            var stats = new Statistics { AvgCmc = avgCmc, ColorRatio = coloreRat, TypeRatio = typeRat };
            var deck = new Deck {
                CardsCount = d.cards_count,
                DeckID = d.deck_id,
                Description = d.description,
                Name = d.name,
                MaxCardsCount = d.max_cards_count,
                Stars = d.stars,
                PlayerID = d.player_id,
                DeletedAt = d.deleted_at,
                Statistics = stats,
                Rank = rank
            };

            foreach (var c in cards) {
                foreach (var l in cds) {
                    if (l.deck_id == ID && l.card_id == c.CardID) {
                        cardsWCount.Add(c,l.count);
                    }
                }
            }
            var karty = new CardListViewModel {Cards = cards, CardsCount = cardsWCount}; //List ze selectu karet
            var balicek = deck; //Model deck z DAO decku
            var hraciselect = new PlayerSelectViewModel //Dropdown List ze selectu hráčů
                {Players = new SelectList(players, "PlayerID", "Login")};
            var komenty = new CommentListViewModel {Comments = comments}; //List ze selectu komentářů
            var kartyselect = new CardSelectViewModel //Dropdown list ze selectu karet
                {Cards = new SelectList(cards, "CardID", "Name")};

           
            model.PlayerSelect = hraciselect;
            model.Deck = balicek;
            model.CardList = karty;
            model.CardSelect = kartyselect;
            model.CommentList = komenty;

            return model;
        }

        public static IEnumerable<Deck> GimmeDecks(IEnumerable<Decks> decksTableSelect) {
            var decks = new Collection<Deck>();
            foreach (var d in decksTableSelect) {
                var deck = new Deck {
                    CardsCount = d.cards_count,
                    DeckID = d.deck_id,
                    Description = d.description,
                    Name = d.name,
                    MaxCardsCount = d.max_cards_count,
                    Stars = d.stars,
                    PlayerID = d.player_id,
                    DeletedAt = d.deleted_at
                };
                decks.Add(deck);
            }

            return decks;
        }
    }
}

Views/Cards/AddCardToDeck.cshtml
@model CardDeck

@{ ViewData["Title"] = "Add card to deck";
}
<h1 style="color:#acdc42" class="display-4">@ViewData["Title"]</h1>
Do you want to add card @Model.CardID in deck @Model.DeckID: @Model.Count x times? 

Views/Cards/CardsList.cshtml
@model WebApplication2.ViewModels.CardListViewModel

@{
    
    ViewData["Title"] = "All Cards";
    
}

<h1 style="color:#acdc42" class="display-4">@ViewData["Title"]</h1> <br/>


        <div class="panel-body">
            <table class="table table-striped" style="white-space:nowrap">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Set code</th>
                        <th>Type</th>
                        <th>Color</th>
                        <th>CMC</th>
                        <th>Rarity</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Card card in Model.Cards)
                    {
                        <tr>
                            <td>@card.CardID</td>
                            <td><a  asp-area="" asp-controller="Cards" asp-route-multiverseID=@card.CardID asp-action="Detail">@card.Name</a></td>
                            <td>@card.SetCode</td>
                            <td>@card.Type</td>
                            <td>@card.Color</td>
                            <td>@card.CMC</td>
                            <td>@card.Rarity</td>
                        </tr>
                    }
                </tbody>
            </table>
</div>

Views/Cards/CardsSearch.cshtml
@model WebApplication2.ViewModels.CardListViewModel

@{
    
    ViewData["Title"] = "Found cards";
    
}

<h1 style="color:#acdc42" class="display-4">@ViewData["Title"]</h1> <br/>


        <div class="panel-body">
            <table class="table table-striped" style="white-space:nowrap">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Set code</th>
                        <th>Type</th>
                        <th>Color</th>
                        <th>CMC</th>
                        <th>Rarity</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Card card in Model.Cards)
                    {
                        <tr>
                            <td>@card.CardID</td>
                            <td><a  asp-area="" asp-controller="Cards" asp-route-multiverseID=@card.CardID asp-action="Detail">@card.Name</a></td>
                            <td>@card.SetCode</td>
                            <td>@card.Type</td>
                            <td>@card.Color</td>
                            <td>@card.CMC</td>
                            <td>@card.Rarity</td>
                        </tr>
                    }
                </tbody>
            </table>
</div>

Views/Cards/Detail.cshtml
@model Card
@{

    var id = @ViewData["MultiverseID"];
    ViewData["Title"] = Model.Name;
    ViewData["Image"] = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=" + id + "&type=card";
    
}


<table >
    
    <tr>
        <td >

            <!--Vlevo nahoře-->
            Detail of card
            <h1 style="color:#acdc42" class="display-4">@ViewData["Title"]</h1>
        </td>
        @* <td >

            <!--Vpravo nahoře-->
              Number from URL:
            Card with ID @ViewData["MultiverseID"] <br/><br/><br/>
            <button class="btn btn-primary">//TODO Random</button><br/><br/>
            <button class="btn btn-primary">//TODO Add card to DB</button><br/><br/>
            <button class="btn btn-primary">//TODO Add card to deck</button> 
            
        </td>*@
        <td rowspan="2">
                    <!--Vpravo dole-->
        <div class="text-center">
                    Card from URL (from link and id):<br/>
                    <img src=@ViewData["Image"] alt="CardImage"/><br/><br/>
        </div>
                </td>
    </tr>
    <tr>
        <td>
            <!--Vlevo dole-->

            Card Info from database:
            <table class="table-striped">
                <tr>
                    <td>Name:</td> <td style="color:#eeeeee"><b>@Model.Name</b></td>
                </tr>
                <tr>
                    <td >Set:</td> <td style="color:#eeeeee"><b>@Model.SetCode</b></td>
                </tr>
                <tr>
                    <td >Type:</td> <td style="color:#eeeeee"><b>@Model.Type</b></td>
                </tr>
                <tr>
                    <td >Color:</td> <td style="color:#eeeeee"><b>@Model.Color</b></td>
                </tr>
                <tr>
                    <td >Artist:</td> <td style="color:#eeeeee"><b>@Model.Artist</b></td>
                </tr>
            </table>

        </td>
        
    </tr>
</table>

Views/Cards/Index.cshtml
@model WebApplication2.ViewModels.CardIndexForm
@{
    ViewData["Title"] = "Cards";
}
<h1 style="color:#acdc42" class="display-4">@ViewData["Title"]</h1>
<table>
    <tr>
        <td>
            <h3>Search cards</h3> <br/>
            <div class="text-center">
                <form asp-controller="Cards" asp-action="CardsSearch">
                    <!--asp-controller="SLOŽKA" asp-action="CSHTML-->

                    <p>
                        <input type="text" name="searchStr"/><br/><br/>
                        <input class="btn btn-primary" type="submit" value="Search"/>
                    </p>
                </form> <br/>
                <h3>
                    <a asp-area="" asp-controller="Cards" asp-action="CardsList">View All Cards</a>
                </h3>
            </div>
        </td>
        <td rowspan="2">
            <h3>Most used cards in decks of most rating player</h3>

 <form asp-action="Index" asp-controller="Cards">
                                <div class="form-group">
            <table style="white-space:nowrap">
                <thead>
                <tr>
                    <th>
                        Cards
                    </th>
                    <th>Add</th>
                </tr>
                </thead>
                <tbody>
                @foreach (Card card in Model.CardList.Cards) {
                    <tr>
                        <td>
                            <a asp-area="" asp-controller="Cards" asp-route-multiverseID=@card.CardID asp-action="Detail">@card.Name</a>
                        </td>


                        <td>
                            
                            <a asp-area="" asp-controller="Cards" asp-route-CardID=@card.CardID asp-action="Index"> <input type="submit" class="btn btn-primary" name="@card.CardID" value="@card.CardID"></a>
                           

                        </td>
                    </tr>
                }
                <tr>
                    <td colspan="2">
                        <div class="text-right">
                            @*   Select a deck to add a card: <br/> @Html.DropDownListFor(x => x.DeckSelect.SelectedDeck, Model.DeckSelect.Decks, "Select a deck")
                   *@
                           
                                    <label asp-for="DeckSelect.SelectedDeck.DeckID">Select a deck to add a card<span class="text-danger">*</span>:</label>
                                    <select class="form-control" asp-for="DeckSelect.SelectedDeck.DeckID">
                                        <option value="0">Select a card</option>
                                        @foreach (var deck in Model.DeckSelect.Decks) {
                                            <option value=@deck.Value>@deck.Text</option> @*Value is DeckID, Text is Name*@
                                        }
                                    </select>
                                
                        </div>
                    </td>

                </tr>
                </tbody>
            </table>
            </div>
            
                                        </form>

            <br>
        </td>
    </tr>
    <tr>
        <td>
            <h3>Best decks</h3>
            <div class="panel-body">
                <table class="table table-striped" style="white-space:nowrap">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Owner ID</th>
                        <th>Stars</th>
                        <th>Cards</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (Deck deck in Model.DeckList.Decks) {
                        <tr>
                            <td>@deck.DeckID</td>
                            <td>
                                <a asp-area="" asp-controller="Decks" asp-route-ID=@deck.DeckID asp-action="Detail">@deck.Name</a>
                            </td>
                            <td>@deck.PlayerID</td>
                            <td>@deck.Stars</td>
                            <td>@deck.CardsCount</td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </td>

    </tr>


</table>